fix: fix type annotation of container check_infos in ops.testing (#1784)
Testing code such as `container = testing.Container("db",
check_infos={check_info})` was failing type checks, with this error:

```
error: Argument of type "set[CheckInfo]" cannot be assigned to parameter "check_infos" of type "frozenset[CheckInfo]" in function "__init__"
    "set[CheckInfo]" is not assignable to "frozenset[CheckInfo]" (reportArgumentType)
```

This PR fixes the type annotation of `check_infos` so that non-frozen
sets are acceptable.