ci: store the charmcraft logs if packing fails (#1936)
If the charmcraft pack workflow fails, we get output like:

```
Run sudo charmcraft pack --verbose
Starting charmcraft, version 3.5.2
Logging execution to '/root/.local/state/charmcraft/log/charmcraft-20250730-063104.414518.log'
Launching managed ubuntu 20.04 instance...
Creating new instance from remote
Creating new base instance from remote
Creating new instance from base instance
Starting instance
Starting charmcraft, version 3.5.2
Logging execution to '/tmp/charmcraft.log'
Initialising lifecycle
Installing build-packages
Failed to refresh package list: failed to run apt update.
Failed to execute charmcraft in instance.
Full execution log: '/root/.local/state/charmcraft/log/charmcraft-20250730-063104.414518.log'
Error: Process completed with exit code 1.
```

This doesn't really tell us what went wrong. This PR will store the
charmcraft log if packing fails, so that the error can be more easily
investigated.