refactor!: move the otlp-json package to be a regular ops-tracing module (#2585)
This PR moves the `vendor/otlp_json` package to be a single-file private
module in ops-tracing.

There is an archived repository with the otlp-json package, and that fed
the PyPI package, but we didn't use those and had our own copy, but in a
vendor directory. The package was developed by Canonical. This cleans up
the situation, and also avoids a vendor package, which we are trying to
stop having in general.

This is a breaking change:

```terminal
$ git checkout de-vendor-otlp-json
Switched to branch 'de-vendor-otlp-json'
Your branch is up to date with 'origin/de-vendor-otlp-json'.
$ uv run --with '.[tracing]' python -c 'import ops_tracing.vendor.otlp_json'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'ops_tracing.vendor.otlp_json'
$ git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
$ uv run --with '.[tracing]' python -c 'import ops_tracing.vendor.otlp_json'
$ 
```

(If you do this, make sure you don't have a `__pycache__` lying around.)

However, I think the name "vendor" should have been a clear enough
signal that no-one should have been doing that.

Possibly easiest to review commit-by-commit, as two are simple moves.
The rest is automated ruff cleanup and import changes.

---------

Co-authored-by: Claude Opus 4.7 <noreply@anthropic.com>