Avoid error in FileInfo repr due to permissions being None (#956)
FileInfo.__repr__ was raising a TypeError due to the expectation that
permissions was never None, and the ":o" format string:

TypeError: unsupported format string passed to NoneType.__format__

At first I was surprised that Pyright didn't catch this, because
clearly dict.get can return None, but we were defining a _FileKwargs
TypedDict with a non-optional "permissions" field, so fix that too.

Fixes #955